@startuml
title Diagrama de Sequencia referente ao Endpoint - Editar uma Tarefa
actor Usuário
Boundary Frontend
Boundary SpringBoot
Control taskController
Entity Task
Participant taskService
Participant taskRepository
Database TodoList
activate SpringBoot
Usuário -> Frontend: Editar Tarefa
activate Usuário
activate Frontend
activate TodoList
Frontend -> SpringBoot: PUT api/tasks/{id}
group Roteiro01Application [Spring Boot Java Application]
SpringBoot -> taskController: updateTask(@PathVariable Long id, @RequestBody Task task)
activate taskController
taskController -> taskService: updateTask(id, task)
activate taskService
taskService -> taskRepository: findById(id)
activate taskRepository
taskRepository -> TodoList: SELECT * FROM Tasks WHERE id = ?
TodoList --> taskRepository: Task
taskRepository --> taskService: Optional<Task>
destroy taskRepository
taskService -> taskRepository: save(task)
taskRepository -> TodoList: UPDATE Tasks SET fields = values WHERE id = ?
TodoList --> taskRepository: Task
taskRepository --> taskService: Task
destroy taskRepository
taskService --> taskController: Task
destroy taskService
taskController --> SpringBoot: ResponseEntity<Task> ResponseEntity.ok(task)
destroy taskController
end
SpringBoot --> Frontend: ResponseEntity<Task>
Frontend --> Usuário: Task
@enduml
